
version: '3'

tasks:
  # --- DEFAULTS ---
  default:
    desc: Start server then run full validations (server + web)
    deps: [validate-all]

  # --- COMMANDS ---
  validate-all:
    desc: Start Python server in background, then run server and web validations (all checks)
    cmds:
      - task: validate-server
      - task: validate-web

  validate-server:
    desc: Server-side checks like deps, formatting, lint, unit and integration tests
    dir: server
    cmds:
      - pip install -r requirements.txt
      - black --check .
      - flake8 .
      - pytest tests/unit
      - pytest tests/integration

  validate-web:
    desc: Web checks like install, lint, format, component and integration tests
    dir: web
    cmds:
      - pnpm install
      - pnpm run lint
      - pnpm run format
      - pnpm run test:component:run
      - pnpm run test:integration:run
