
version: '3'

tasks:
  default:
    deps: [validate-api]

  validate-api:
    desc: Server-side checks like deps, formatting, lint, unit and integration tests
    cmds:
      - pip install -r requirements.txt
      - black --check .
      - flake8 .
      - pytest tests/unit
      - pytest tests/integration
